language: rust
sudo: false
script:
    - cargo build
    - cargo test
    - cargo doc --no-deps
after_success: |
    [ $TRAVIS_BRANCH = master ] &&
    [ $TRAVIS_PULL_REQUEST = false ] &&
    bash deploy-docs.sh
