language: rust
sudo: false
matrix:
    include:
        - rust: stable
          env:
              - --features='linear-map vec_map'
        - rust: nightly
          env:
              - --features='linear-map linked-hash-map vec_map'
script:
    - cargo build $FEATURES
    - cargo test $FEATURES
    - cargo doc --no-deps $FEATURES
after_success: |
    [ $TRAVIS_TAG ] &&
    [ $TRAVIS_RUST_VERSION = stable ] &&
    bash deploy-docs.sh
