language: rust
sudo: false
matrix:
    include:
        - rust: nightly
          env: FEATURES="--features nightly"
        - rust: beta
script:
    - cargo build $FEATURES
    - cargo test $FEATURES
    - cargo doc --no-deps $FEATURES
after_success: |
    [ $TRAVIS_TAG ] &&
    [ $TRAVIS_BRANCH = master ]
    bash deploy-docs.sh
