language: rust
sudo: false
matrix:
    include:
        - rust: stable
          env:
              - FEATURES='linear-map vec_map'
        - rust: nightly
          env:
              - FEATURES='nightly linear-map linked-hash-map vec_map'
script:
    - cargo build --features "$FEATURES"
    - cargo test --features "$FEATURES"
    - cargo doc --no-deps --features "$FEATURES"
after_success: |
    [ $TRAVIS_TAG ] &&
    [ $TRAVIS_RUST_VERSION = stable ] &&
    bash deploy-docs.sh
