language: rust
sudo: false
matrix:
    include:
        - rust: stable
        - rust: nightly
script:
    - cargo build
    - cargo test
    - cargo doc --no-deps
after_success: |
    [ $TRAVIS_TAG ] &&
    [ $TRAVIS_RUST_VERSION = stable ] &&
    bash deploy-docs.sh
